#!/usr/bin/env python3
"""Push augur's issues.json to GitHub Issues.

Usage:
    python create-issues.py <project-path> [--dry-run] [--auto]

Reads:
    <project>/.kord/agents/augur/memory/issues.json

Deduplicates against existing GitHub issues, then creates new ones.
Requires: gh CLI authenticated with repo access.
"""

import json
import subprocess
import sys
from pathlib import Path


LABEL_COLORS = {
    "bug": "d73a4a",
    "enhancement": "a2eeef",
    "suggestion": "c5def5",
    "debt": "fbca04",
    "reliability": "e4e669",
    "priority:high": "b60205",
    "gap": "d4c5f9",
    "observation": "bfdadc",
}


def run_gh(args: list[str], check=True) -> str:
    result = subprocess.run(["gh"] + args, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"gh error: {result.stderr}", file=sys.stderr)
    return result.stdout.strip()


def discover_project(arg: str) -> Path:
    candidates = [
        Path(arg),
        Path(f"/kord/projects/{arg}"),
        Path.home() / arg,
        Path.home() / "repos" / arg,
    ]
    for p in candidates:
        if p.is_dir():
            return p.resolve()
    print(f"Error: project '{arg}' not found.", file=sys.stderr)
    sys.exit(1)


def detect_repo(project_dir: Path) -> str | None:
    result = subprocess.run(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
        capture_output=True, text=True, cwd=project_dir,
    )
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return None


def fetch_existing_issues(repo: str) -> list[dict]:
    issues = []
    for state in ["open", "closed"]:
        limit = 200 if state == "open" else 100
        out = run_gh([
            "issue", "list", "--repo", repo, "--state", state,
            "--limit", str(limit), "--json", "number,title,body,labels",
        ], check=False)
        if out:
            try:
                issues.extend(json.loads(out))
            except json.JSONDecodeError:
                pass
    return issues


def deduplicate(findings: list[dict], existing: list[dict]) -> list[dict]:
    stopwords = {"the", "a", "an", "in", "to", "for", "of", "and", "or", "is", "on", "at", "by"}
    for finding in findings:
        for issue in existing:
            title_words = set(finding["title"].lower().split()) - stopwords
            issue_words = set(issue.get("title", "").lower().split()) - stopwords
            body = issue.get("body", "") or ""

            if finding["source_id"] in body:
                finding["duplicate_of"] = issue["number"]
                break

            if len(title_words & issue_words) >= 2:
                finding["duplicate_of"] = issue["number"]
                break

            for f in finding.get("files", []):
                if isinstance(f, str) and f in body:
                    finding["duplicate_of"] = issue["number"]
                    break
            if "duplicate_of" in finding:
                break

    return findings


def format_issue_body(finding: dict) -> str:
    parts = ["## Finding", "", finding["body"] or finding["title"]]

    if finding["files"]:
        parts.extend(["", "## Affected files", ""])
        for f in finding["files"]:
            parts.append(f"- `{f}`")

    if finding["recommendation"]:
        parts.extend(["", "## Recommendation", "", finding["recommendation"]])

    if finding["evidence"]:
        parts.extend(["", "## Evidence", "", str(finding["evidence"])])

    parts.extend([
        "", "---", "",
        f"<sub>Source: `{finding['source_id']}` | Generated by augur analysis</sub>",
    ])

    return "\n".join(parts)


def ensure_labels(repo: str, labels: set[str]):
    for label in labels:
        color = LABEL_COLORS.get(label, "ededed")
        run_gh([
            "label", "create", label, "--repo", repo,
            "--description", f"augur: {label}", "--color", color,
        ], check=False)


def main():
    args = sys.argv[1:]
    dry_run = "--dry-run" in args
    auto = "--auto" in args
    project_arg = next((a for a in args if not a.startswith("--")), None)

    if not project_arg:
        print(f"Usage: {sys.argv[0]} <project> [--dry-run] [--auto]", file=sys.stderr)
        sys.exit(1)

    project_dir = discover_project(project_arg)
    project_name = project_dir.name

    # Detect repo
    repo = detect_repo(project_dir)
    if not repo:
        print(f"Error: no GitHub repo found for {project_dir}", file=sys.stderr)
        sys.exit(1)
    print(f"Repo: {repo}")

    # Load issues.json
    issues_path = project_dir / ".kord" / "agents" / "augur" / "memory" / "issues.json"
    if not issues_path.exists():
        print(f"Error: {issues_path} not found. Run augur /analyze first, then extract-issues.py.", file=sys.stderr)
        sys.exit(1)

    with open(issues_path) as f:
        findings = json.load(f)
    print(f"Loaded {len(findings)} issues from {issues_path}")

    # Deduplicate
    existing = fetch_existing_issues(repo)
    print(f"Fetched {len(existing)} existing GitHub issues")
    findings = deduplicate(findings, existing)

    new = [f for f in findings if "duplicate_of" not in f]
    dupes = [f for f in findings if "duplicate_of" in f]

    # Report
    print(f"\n## Proposed Issues for {project_name}\n")
    print(f"### Will create ({len(new)})\n")
    if new:
        print(f"{'#':>3} | {'Type':<12} | {'Title':<50} | Labels")
        print(f"{'---':>3} | {'---':<12} | {'---':<50} | ---")
        for i, f in enumerate(new, 1):
            print(f"{i:>3} | {f['classification']:<12} | {f['title'][:50]:<50} | {', '.join(f['labels'])}")

    if dupes:
        print(f"\n### Skipped — duplicates ({len(dupes)})\n")
        for f in dupes:
            print(f"  {f['title'][:60]} -> #{f['duplicate_of']}")

    if dry_run:
        print("\n--dry-run: stopping here.")
        return

    if not auto and new:
        print(f"\nProceed with creating {len(new)} issues? [y/N] ", end="", flush=True)
        if input().strip().lower() != "y":
            print("Aborted.")
            return

    if not new:
        print("\nNo new issues to create.")
        return

    # Create labels and issues
    all_labels = set()
    for f in new:
        all_labels.update(f["labels"])
    ensure_labels(repo, all_labels)

    created = []
    for f in new:
        body = format_issue_body(f)
        out = run_gh([
            "issue", "create", "--repo", repo,
            "--title", f["title"],
            "--body", body,
            "--label", ",".join(f["labels"]),
        ])
        if out:
            print(f"  Created: {out}")
            created.append(out)

    bugs = sum(1 for f in new if f["classification"] == "bug")
    enhancements = sum(1 for f in new if f["classification"] == "enhancement")
    suggestions = sum(1 for f in new if f["classification"] == "suggestion")

    print(f"\n## Issues: {project_name}")
    print(f"Repo: {repo}")
    print(f"Created: {len(created)} ({bugs} bugs, {enhancements} enhancements, {suggestions} suggestions)")
    print(f"Skipped: {len(dupes)} duplicates")


if __name__ == "__main__":
    main()
