#!/usr/bin/env python3
"""Generate Astro journey pages for a project using shared components.

Usage:
    python generate-pages.py <project-path>

Reads:
    <project>/.kord/agents/augur/memory/atlas.json (for project name verification)

Writes directly to the docs repo:
    <docs>/src/pages/<project>/index.astro
    <docs>/src/pages/<project>/atlas/index.astro

Pages use shared components from src/components/journey/.
"""

import json
import sys
from pathlib import Path


DOCS_CANDIDATES = [
    Path("/kord/projects/docs"),
    Path.home() / "projects" / "docs",
    Path.home() / "repos" / "docs",
]


def discover_project(arg: str) -> Path:
    candidates = [
        Path(arg),
        Path(f"/kord/projects/{arg}"),
        Path.home() / arg,
        Path.home() / "repos" / arg,
    ]
    for p in candidates:
        if p.is_dir():
            return p.resolve()
    print(f"Error: project '{arg}' not found.", file=sys.stderr)
    sys.exit(1)


def find_docs_repo() -> Path:
    for p in DOCS_CANDIDATES:
        if p.is_dir() and (p / "astro.config.mjs").exists():
            return p
    print("Error: docs repo not found.", file=sys.stderr)
    sys.exit(1)


def generate_journey_page(project_name: str, content_dir: str) -> str:
    # Use a template string. Astro uses { } for expressions, so we
    # write the Astro file literally and only interpolate Python vars
    # (project_name, content_dir) which are plain strings.
    return (
        '---\n'
        '/**\n'
        f' * {project_name} Journey — Guided architecture walkthrough\n'
        ' * Auto-generated by generate-pages.py from augur analysis.\n'
        ' */\n'
        "import Base from '../../layouts/Base.astro';\n"
        "import Header from '../../components/Header.astro';\n"
        "import JourneyStyles from '../../components/journey/JourneyStyles.astro';\n"
        "import JourneyNav from '../../components/journey/JourneyNav.astro';\n"
        "import LandingSection from '../../components/journey/LandingSection.astro';\n"
        "import OverviewSection from '../../components/journey/OverviewSection.astro';\n"
        "import StorySection from '../../components/journey/StorySection.astro';\n"
        "import FocusOverlay from '../../components/journey/FocusOverlay.astro';\n"
        "import Drawer from '../../components/journey/Drawer.astro';\n"
        "import JourneyData from '../../components/journey/JourneyData.astro';\n"
        "import JourneyScript from '../../components/journey/JourneyScript.astro';\n"
        "import fs from 'node:fs';\n"
        "import yaml from 'js-yaml';\n"
        '\n'
        f"const dir = '{content_dir}';\n"
        "const atlas = JSON.parse(fs.readFileSync(`${dir}/atlas.json`, 'utf-8'));\n"
        "const manifest = JSON.parse(fs.readFileSync(`${dir}/manifest.json`, 'utf-8'));\n"
        "const storyByNode = JSON.parse(fs.readFileSync(`${dir}/storyByNode.json`, 'utf-8'));\n"
        '\n'
        "const journeyFiles = fs.readdirSync(`${dir}/journeys`).filter((f: string) => f.endsWith('.yaml'));\n"
        "const journeys = journeyFiles.map((f: string) => yaml.load(fs.readFileSync(`${dir}/journeys/${f}`, 'utf-8')));\n"
        "const defaultJourney = journeys.find((j: any) => j.id === 'getting-started') || journeys[0];\n"
        '\n'
        'const storyMap: Record<string, any> = {};\n'
        "for (const f of fs.readdirSync(`${dir}/stories`).filter((s: string) => s.endsWith('.yaml'))) {\n"
        "  const s = yaml.load(fs.readFileSync(`${dir}/stories/${f}`, 'utf-8')) as any;\n"
        '  storyMap[s.id] = s;\n'
        '}\n'
        '\n'
        'const journeyData: Record<string, { stories: any[]; bridgeMap: Record<string, any>; total: number }> = {};\n'
        'for (const j of journeys) {\n'
        '  const jStories = (j.stories || []).map((sid: string) => storyMap[sid]).filter(Boolean);\n'
        '  const jBridges: Record<string, any> = {};\n'
        '  for (const b of (j.bridges || [])) {\n'
        "    if (b && typeof b === 'object') jBridges[b.to] = b;\n"
        '  }\n'
        '  journeyData[j.id] = { stories: jStories, bridgeMap: jBridges, total: jStories.length };\n'
        '}\n'
        '\n'
        'const stories = journeyData[defaultJourney.id]?.stories || [];\n'
        'const compMap: Record<string, any> = {};\n'
        'for (const c of (atlas.components || [])) compMap[c.id] = c;\n'
        'for (const e of (atlas.external_dependencies || [])) compMap[e.id] = e;\n'
        '\n'
        "const purpose = atlas.purpose || '';\n"
        '\n'
        'function parseSummary(text: string): string {\n'
        '  return text\n'
        '    .replace(/\\*\\*([^*]+?)\\*\\*/gs, (_: string, name: string) =>\n'
        '      `<span class="ref" data-id="${name.toLowerCase().replace(/\\s+/g, \'-\')}">${name}</span>`)\n'
        "    .replace(/\\n\\n/g, '<br><br>')\n"
        "    .replace(/\\n/g, ' ');\n"
        '}\n'
        '---\n'
        '\n'
        '<Base title={defaultJourney.title}>\n'
        '  <JourneyStyles />\n'
        '\n'
        f"  <Header project={{atlas.project || '{project_name}'}} badge=\"dev\" links={{[{{ label: 'Atlas', href: '/dev/{project_name}/atlas/' }}, {{ label: 'Issues', href: '/dev/{project_name}/issues/' }}]}} active=\"journey\" />\n"
        '\n'
        '  <JourneyNav journeys={journeys} defaultJourney={defaultJourney} stories={stories} />\n'
        '\n'
        '  <LandingSection\n'
        f"    project={{atlas.project || '{project_name}'}}\n"
        '    purpose={purpose}\n'
        '    journeys={journeys}\n'
        '    defaultJourney={defaultJourney}\n'
        '    totalStories={stories.length}\n'
        '    domainModel={atlas.domain_model}\n'
        '    componentCount={atlas.components?.length}\n'
        '    flowCount={atlas.flows?.length}\n'
        '  />\n'
        '\n'
        '  <OverviewSection atlas={atlas} journeys={journeys} defaultJourney={defaultJourney} storyByNode={storyByNode} />\n'
        '\n'
        '  {journeys.map((journey: any) => {\n'
        '    const jd = journeyData[journey.id];\n'
        '    const isDefault = journey.id === defaultJourney.id;\n'
        '    return jd.stories.map((story: any, i: number) => (\n'
        '      <StorySection\n'
        '        story={story}\n'
        '        index={i}\n'
        '        total={jd.total}\n'
        '        journeyId={journey.id}\n'
        '        isDefault={isDefault}\n'
        '        bridge={jd.bridgeMap[story.id]}\n'
        '        compMap={compMap}\n'
        '        storyByNode={storyByNode}\n'
        '        parseSummary={parseSummary}\n'
        '      />\n'
        '    ));\n'
        '  })}\n'
        '\n'
        '  <FocusOverlay />\n'
        '  <JourneyData atlas={atlas} storyByNode={storyByNode} />\n'
        f"  <Drawer project={{atlas.project || '{project_name}'}} />\n"
        '  <JourneyScript />\n'
        '</Base>\n'
    )


def generate_atlas_page(project_name: str, content_dir: str) -> str:
    return (
        '---\n'
        '/**\n'
        f' * {project_name} Atlas — Full reference view\n'
        ' * Auto-generated by generate-pages.py from augur analysis.\n'
        ' */\n'
        "import Base from '../../../layouts/Base.astro';\n"
        "import Header from '../../../components/Header.astro';\n"
        "import fs from 'node:fs';\n"
        '\n'
        f"const dir = '{content_dir}';\n"
        "const atlas = JSON.parse(fs.readFileSync(`${dir}/atlas.json`, 'utf-8'));\n"
        '---\n'
        '\n'
        f'<Base title="{project_name} Atlas">\n'
        f"  <Header project={{atlas.project || '{project_name}'}} badge=\"dev\" links={{[{{ label: 'Journey', href: '/dev/{project_name}/' }}, {{ label: 'Issues', href: '/dev/{project_name}/issues/' }}]}} active=\"atlas\" />\n"
        '  <div style="max-width:900px;margin:0 auto;padding:80px 1.5rem 4rem;">\n'
        f'    <h1 style="font-size:2rem;font-weight:700;margin-bottom:.5rem;">{project_name} Atlas</h1>\n'
        '    <p style="color:var(--text-3);margin-bottom:2rem;">{atlas.purpose}</p>\n'
        '    <p style="color:var(--text-4);font-size:.8rem;">Full atlas view coming soon. Use the Journey view for the guided walkthrough.</p>\n'
        '  </div>\n'
        '</Base>\n'
    )


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <project-path>", file=sys.stderr)
        sys.exit(1)

    project_dir = discover_project(sys.argv[1])
    project_name = project_dir.name
    docs_repo = find_docs_repo()

    # Verify augur output exists
    augur_dir = project_dir / ".kord" / "agents" / "augur" / "memory"
    if not (augur_dir / "atlas.json").exists():
        print(f"Error: {augur_dir / 'atlas.json'} not found.", file=sys.stderr)
        sys.exit(1)

    content_dir = f"src/content/docs/{project_name}"

    # Output
    pages_dir = docs_repo / "src" / "pages" / project_name
    atlas_dir = pages_dir / "atlas"
    pages_dir.mkdir(parents=True, exist_ok=True)
    atlas_dir.mkdir(parents=True, exist_ok=True)

    (pages_dir / "index.astro").write_text(generate_journey_page(project_name, content_dir))
    print(f"  wrote {pages_dir / 'index.astro'}")

    (atlas_dir / "index.astro").write_text(generate_atlas_page(project_name, content_dir))
    print(f"  wrote {atlas_dir / 'index.astro'}")

    print(f"\nGenerated 1 journey page + 1 atlas page for {project_name}")
    print(f"Pages: {pages_dir}")


if __name__ == "__main__":
    main()
